openapi: 3.0.0
info:
  title: User Data API
  description: API to manage user data
  version: 1.0.0
paths:
  /api/users:
    get:
      summary: Get all users
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    username:
                      type: string
                    email:
                      type: string
